// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTable: typeof import('./src/components/BaseTable/index.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    MyLink: typeof import('./src/components/MyLink/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VPlotly: typeof import('./src/components/VPlotly/index.vue')['default']
  }
}

export {}
